[phases.setup]
cmds = ["pip install --upgrade pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn newsletter.wsgi:application --bind 0.0.0.0:$PORT"

[build.args]
PYTHON_VERSION = "3.11"