[phases.setup]
cmds = ["pip install -r requirements.txt"]

[phases.install]
cmds = ["python manage.py collectstatic --noinput"]

[phases.build]
cmds = []

[start]
cmd = "gunicorn your_project.wsgi:application"